# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "WIWIWK"
subtitle: "What I Wish I Would've Known"
email: david.wang15275-binj@basischina.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a website about what many people wish they would've known before
  they stepped into college. Created as a school project.
baseurl: "/wiwiwk" # the subpath of your site, e.g. /blog
url: "https://david-why.tech" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: dark
plugins:
  - jekyll-archives

include:
  - _pages

defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
  # posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      share: true
      show_date: true
      permalink: /:categories/:title/
  - scope:
      path: "_posts/Speaker"
      type: posts
    values:
      categories: [Speaker]

breadcrumbs: true

jekyll-archives:
  enabled:
    - categories
  permalinks:
    category: '/:name/'
  layout: jekyll-archive

atom_feed:
  hide: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
